/* This file was generated by the "svnrev" utility
 * (https://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 6974M$
 * $Date: 2023-08-08$
 */

#ifndef _SVNREV_H_
#define _SVNREV_H_

#define SVNREV_NUM	6974
#define SVNREV_STR	"6974M"
#define SVNREV_RCS	"$Revision: 6974M $"
#define SVNREV_DATE	"2023-08-08"
#define SVNREV_STAMP	20230808L
#define SVNREV_MODIFIED	1

#endif /* _SVNREV_H_ */
