/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 5091$
 * $Date: 2014-06-26$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		5091
#define SVN_REVSTR	"5091"
#define SVN_REVDATE	"2014-06-26"
#define SVN_REVSTAMP	20140626L
#define SVN_REVMODIFIED	0

#endif /* SVN_REV_H */
